// Mock data para BlackSheep - Data simulada que se comparte entre admin y app
import type {
  FitCenterUserProfile,
  Discipline,
  ClassSession,
  MembershipPlan,
  Organization,
  Instructor,
  ClassSessionExtended,
} from "@/lib/types";

// === INTERFACES ESPECÍFICAS PARA LA VISTA CLIENTE ===
export interface ClassItem {
  id: string;
  dateTime: string;
  name: string;
  instructor: string;
  duration: string;
  alumnRegistred: string;
  isRegistered: boolean;
  status?: "scheduled" | "cancelled" | "completed" | "in_progress";
}

// === DATOS INICIALES MEJORADOS ===

export const initialOrganization: Organization = {
  id: "org_blacksheep_001", // ID de la organización BlackSheep
  name: "BlackSheep CrossFit", // Nombre de BlackSheep
  description: "Tu box de CrossFit en Los Ángeles",
  type: "crossfit",
  branding: {
    primaryColor: "#0A0A0A", // Colores de BlackSheep
    secondaryColor: "#FFD700",
    logoSvg: "",
  },
  settings: {
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es",
    defaultCancellationHours: 2, // Ajustado a BlackSheep mock
    maxBookingsPerDay: 2, // Ajustado a BlackSheep mock
    waitlistEnabled: true, // Ajustado a BlackSheep mock
    operatingHours: [
      { day: "lun", open: "06:00", close: "22:00", closed: false },
      { day: "mar", open: "06:00", close: "22:00", closed: false },
      { day: "mie", open: "06:00", close: "22:00", closed: false },
      { day: "jue", open: "06:00", close: "22:00", closed: false },
      { day: "vie", open: "06:00", close: "22:00", closed: false },
      { day: "sab", open: "08:00", close: "14:00", closed: false },
      { day: "dom", open: "09:00", close: "13:00", closed: false },
    ],
  },
};

export const initialDisciplines: Discipline[] = [
  {
    id: "disc_crossfit_001",
    name: "CrossFit",
    description: "Entrenamiento funcional de alta intensidad.",
    color: "#FF5733",
    isActive: true,
    schedule: [
      {
        day: "lun",
        times: ["05:45", "08:10", "09:10", "18:00", "19:00", "20:00"],
      },
      {
        day: "mar",
        times: ["05:45", "08:10", "09:10", "18:00", "19:00", "20:00"],
      },
      {
        day: "mie",
        times: ["05:45", "08:10", "09:10", "18:00", "19:00", "20:00"],
      },
      {
        day: "jue",
        times: ["05:45", "08:10", "09:10", "18:00", "19:00", "20:00"],
      },
      {
        day: "vie",
        times: ["05:45", "08:10", "09:10", "18:00", "19:00", "20:00"],
      },
    ],
    cancellationRules: [
      {
        id: "rule_0545_6h",
        time: "05:45",
        hoursBefore: 6,
        priority: 1,
        description: "Clases muy tempranas - 6 horas antes",
      },
      {
        id: "rule_0810_2h",
        time: "08:10",
        hoursBefore: 2,
        priority: 1,
        description: "Clases de 8:10 AM - 2 horas antes",
      },
      {
        id: "rule_1800_30min",
        time: "18:00",
        hoursBefore: 0.5,
        priority: 1,
        description: "Clases de 6:00 PM - 30 minutos antes",
      },
      {
        id: "rule_1900_30min",
        time: "19:00",
        hoursBefore: 0.5,
        priority: 1,
        description: "Clases de 7:00 PM - 30 minutos antes",
      },
      {
        id: "rule_2000_30min",
        time: "20:00",
        hoursBefore: 0.5,
        priority: 1,
        description: "Clases de 8:00 PM - 30 minutos antes",
      },
    ],
  },
  {
    id: "disc_crossbalance_001",
    name: "Cross Balance",
    description: "Clases de equilibrio y movilidad.",
    color: "#3357FF",
    isActive: true,
    schedule: [{ day: "sab", times: ["10:00"] }],
    cancellationRules: [],
  },
  {
    id: "disc_weightlifting_001",
    name: "Weightlifting",
    description: "Clases de levantamiento olímpico.",
    color: "#33FF57",
    isActive: true,
    schedule: [{ day: "sab", times: ["11:30"] }],
    cancellationRules: [],
  },
  {
    id: "disc_pilates_001",
    name: "Pilates",
    description: "Clases de pilates para todos los niveles.",
    color: "#FFD700",
    isActive: true,
    schedule: [
      { day: "lun", times: ["11:30"] },
      { day: "mar", times: ["11:30"] },
      { day: "mie", times: ["11:30"] },
      { day: "jue", times: ["11:30"] },
      { day: "vie", times: ["11:30"] },
      { day: "sab", times: ["11:30"] },
    ],
    cancellationRules: [],
  },
];

export const initialMembershipPlans: MembershipPlan[] = [
  {
    id: "plan_full_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Full",
    description: "24 clases al mes",
    price: 50000,
    durationInMonths: 1,
    classLimit: 24,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_intermedio_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Intermedio",
    description: "15 clases al mes",
    price: 42500,
    durationInMonths: 1,
    classLimit: 15,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_basico_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Básico",
    description: "10 clases al mes",
    price: 35000,
    durationInMonths: 1,
    classLimit: 10,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_full_am_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Full AM",
    description: "24 clases al mes (AM)",
    price: 40000,
    durationInMonths: 1,
    classLimit: 24,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_intermedio_am_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Intermedio AM",
    description: "15 clases al mes (AM)",
    price: 35000,
    durationInMonths: 1,
    classLimit: 15,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_basico_am_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Básico AM",
    description: "10 clases al mes (AM)",
    price: 28000,
    durationInMonths: 1,
    classLimit: 10,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  // Planes con diferentes duraciones para probar la funcionalidad
  {
    id: "plan_trimestral_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Trimestral",
    description: "30 clases por 3 meses",
    price: 90000,
    durationInMonths: 3,
    classLimit: 30,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_semestral_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Semestral",
    description: "60 clases por 6 meses",
    price: 150000,
    durationInMonths: 6,
    classLimit: 60,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  {
    id: "plan_anual_001",
    organizationId: "org_blacksheep_001",
    name: "Plan Anual",
    description: "120 clases por 12 meses",
    price: 250000,
    durationInMonths: 12,
    classLimit: 120,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 7,
    autoRenews: true,
    isActive: true,
  },
  // Plan extra anual (id corregido)
  {
    id: "plan_anual_002",
    organizationId: "org_blacksheep_001",
    name: "Plan Anual Ilimitado",
    description: "Clases ilimitadas por 12 meses",
    price: 480000,
    durationInMonths: 12,
    classLimit: 0,
    disciplineAccess: "all",
    allowedDisciplines: [],
    canFreeze: true,
    freezeDurationDays: 30,
    autoRenews: true,
    isActive: true,
  },
  // Plan extra CrossBalance
  {
    id: "plan_crossbalance_001",
    organizationId: "org_blacksheep_001",
    name: "Plan CrossBalance",
    description: "8 clases de CrossBalance al mes",
    price: 30000,
    durationInMonths: 1,
    classLimit: 8,
    disciplineAccess: "limited",
    allowedDisciplines: ["disc_crossbalance_001"],
    canFreeze: false,
    freezeDurationDays: 0,
    autoRenews: true,
    isActive: true,
  },
];

export const initialInstructors: Instructor[] = [
  {
    id: "inst_vito_001",
    organizationId: "org_blacksheep_001",
    firstName: "Vito",
    lastName: "Corleone",
    email: "vito@blacksheep.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  {
    id: "inst_camilo_001",
    organizationId: "org_blacksheep_001",
    firstName: "Camilo",
    lastName: "Soto",
    email: "camilo@blacksheep.com",
    specialties: ["disc_weightlifting_001"],
    isActive: true,
  },
  {
    id: "inst_manu_001",
    organizationId: "org_blacksheep_001",
    firstName: "Manu",
    lastName: "González",
    email: "manu@blacksheep.com",
    specialties: ["disc_crossbalance_001"],
    isActive: true,
  },
  // Test Instructor 1
  {
    id: "inst_test_001",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 1",
    email: "test.instructor1@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 2
  {
    id: "inst_test_002",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 2",
    email: "test.instructor2@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 3
  {
    id: "inst_test_003",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 3",
    email: "test.instructor3@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 4
  {
    id: "inst_test_004",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 4",
    email: "test.instructor4@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 5
  {
    id: "inst_test_005",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 5",
    email: "test.instructor5@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 6
  {
    id: "inst_test_006",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 6",
    email: "test.instructor6@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 7
  {
    id: "inst_test_007",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 7",
    email: "test.instructor7@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
  // Test Instructor 8
  {
    id: "inst_test_008",
    organizationId: "org_blacksheep_001",
    firstName: "Test",
    lastName: "Instructor 8",
    email: "test.instructor8@email.com",
    specialties: ["disc_crossfit_001"],
    isActive: true,
  },
];

// === PERFIL DE ANTONIA OVEJERO (PARA LA VISTA CLIENTE) ===
export const antoniaOvejeroProfile: FitCenterUserProfile = {
  id: "usr_antonia_abc123",
  firstName: "Antonia",
  lastName: "Ovejero",
  email: "cliente@mail.com",
  phone: "+34 612 345 678",
  dateOfBirth: "1990-05-15",
  avatarId: "avatar_1",
  gender: "Femenino",
  membership: {
    id: "mem_blacksheep_antonia",
    organizationId: "org_blacksheep_001",
    organizationName: "BlackSheep CrossFit",
    status: "expired",
    membershipType: "Básico",
    planId: "plan_basico_001",
    monthlyPrice: 35000,
    startDate: "2025-07-01",
    currentPeriodStart: "2025-07-01",
    currentPeriodEnd: "2025-07-31",
    planConfig: {
      classLimit: 8,
      disciplineAccess: "all",
      allowedDisciplines: [],
      canFreeze: true,
      freezeDurationDays: 7,
      autoRenews: true,
    },
    centerConfig: {
      allowCancellation: true,
      cancellationHours: 2,
      maxBookingsPerDay: 2,
      autoWaitlist: true,
    },
    centerStats: {
      currentMonth: {
        classesAttended: 2,
        classesContracted: 8,
        remainingClasses: 6,
        noShows: 0,
        lastMinuteCancellations: 0,
      },
      totalMonthsActive: 1,
      memberSince: "2025-07-01",
      lifetimeStats: {
        totalClasses: 2,
        totalNoShows: 0,
        averageMonthlyAttendance: 2.0,
        bestMonth: {
          month: "Jul",
          year: 2025,
          count: 2,
        },
      },
    },
  },
};

// Usuario admin de ejemplo para autenticación
export const adminUserProfile: FitCenterUserProfile = {
  id: "usr_admin_001",
  firstName: "Admin",
  lastName: "User",
  email: "admin@mail.com",
  phone: "+56 9 0000 0000",
  avatarId: "avatar_2",
  role: "admin",
  membership: {
    id: "mem_admin_001",
    organizationId: "org_blacksheep_001",
    organizationName: "BlackSheep CrossFit",
    status: "active",
    membershipType: "Admin",
    monthlyPrice: 0,
    startDate: "2025-01-01",
    currentPeriodStart: "2025-01-01",
    currentPeriodEnd: "2025-12-31",
    planConfig: {
      classLimit: 0,
      disciplineAccess: "all",
      allowedDisciplines: [],
      canFreeze: false,
      freezeDurationDays: 0,
      autoRenews: false,
    },
    centerConfig: {
      allowCancellation: false,
      cancellationHours: 0,
      maxBookingsPerDay: 0,
      autoWaitlist: false,
    },
    centerStats: {
      currentMonth: {
        classesAttended: 0,
        classesContracted: 0,
        remainingClasses: 0,
        noShows: 0,
        lastMinuteCancellations: 0,
      },
      totalMonthsActive: 0,
      memberSince: "2025-01-01",
      lifetimeStats: {
        totalClasses: 0,
        totalNoShows: 0,
        averageMonthlyAttendance: 0,
        bestMonth: { month: "N/A", year: 0, count: 0 },
      },
    },
  },
};

// === MOCK UNIFICADO PARA LA VISTA CLIENTE ===
export const antoniaBlackSheepMock = {
  profile: antoniaOvejeroProfile,
  classes: [], // Removed antoniaClasses as it's not used in the actual app
};

export const initialUsers: FitCenterUserProfile[] = [
  antoniaOvejeroProfile,
  adminUserProfile,
  // Pedro Pérez (ACTIVO - ILIMITADO)
  {
    id: "usr_pedro_perez_001",
    firstName: "Pedro",
    lastName: "Pérez",
    email: "pedro@email.com",
    phone: "+56 9 2345 6789",
    dateOfBirth: "1985-08-22",
    gender: "Masculino",
    avatarId: "avatar_2",
    address: "Avenida Central 456, Antofagasta",
    emergencyContact: "Ana Pérez +56 9 3456 7890",
    notes: "Nuevo alumno, necesita orientación",
    formaDePago: "debito",
    membership: {
      id: "mem_pedro_001",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Premium",
      planId: "plan_intermedio_001",
      monthlyPrice: 42500,
      startDate: "2024-11-01",
      currentPeriodStart: "2024-12-01",
      currentPeriodEnd: "2024-12-31",
      planConfig: {
        classLimit: 12,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 15,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 4,
          classesContracted: 12,
          remainingClasses: 8,
          noShows: 1,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 2,
        memberSince: "2024-11-01",
        lifetimeStats: {
          totalClasses: 8,
          totalNoShows: 1,
          averageMonthlyAttendance: 4,
          bestMonth: { month: "Noviembre", year: 2024, count: 4 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Laura Gómez (EXPIRADO)
  {
    id: "usr_laura_gomez_001",
    firstName: "Laura",
    lastName: "Gómez",
    email: "laura@email.com",
    phone: "+56 9 1122 3344",
    dateOfBirth: "1992-11-01",
    gender: "Femenino",
    avatarId: "avatar_3",
    address: "Calle Los Robles 567, Antofagasta",
    emergencyContact: "Carlos Gómez +56 9 5566 7788",
    notes: "Membresía no renovada, contactar para reactivar.",
    membership: {
      id: "mem_blacksheep_laura",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "expired",
      membershipType: "Premium",
      monthlyPrice: 45000,
      startDate: "2025-01-01",
      currentPeriodStart: "2025-06-01",
      currentPeriodEnd: "2025-06-30",
      planConfig: {
        classLimit: 12,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 15,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 12,
          remainingClasses: 12,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 6,
        memberSince: "2025-01-01",
        lifetimeStats: {
          totalClasses: 45,
          totalNoShows: 2,
          averageMonthlyAttendance: 7.5,
          bestMonth: { month: "Mar", year: 2025, count: 12 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
    gamification: {},
  },
  // Carlos Rodríguez (CONGELADO)
  {
    id: "usr_carlos_rodriguez_001",
    firstName: "Carlos",
    lastName: "Rodríguez",
    email: "carlos@email.com",
    phone: "+56 9 3344 5566",
    dateOfBirth: "1988-07-10",
    gender: "Masculino",
    avatarId: "avatar_4",
    address: "Pasaje Los Pinos 890, Antofagasta",
    emergencyContact: "Ana Rodríguez +56 9 7788 9900",
    notes: "Membresía congelada por viaje de trabajo.",
    membership: {
      id: "mem_blacksheep_carlos",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "frozen",
      membershipType: "Básico",
      monthlyPrice: 35000,
      startDate: "2025-03-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 8,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 8,
          remainingClasses: 8,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 4,
        memberSince: "2025-03-01",
        lifetimeStats: {
          totalClasses: 28,
          totalNoShows: 1,
          averageMonthlyAttendance: 7.0,
          bestMonth: { month: "May", year: 2025, count: 9 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
    gamification: {},
  },
  // NUEVO ALUMNO QUE REQUIERE APROBACIÓN
  {
    id: "usr_maria_gonzalez_001",
    firstName: "María",
    lastName: "González",
    email: "maria.gonzalez@email.com",
    phone: "+56 9 1234 5678",
    dateOfBirth: "1990-05-15",
    gender: "Femenino",
    avatarId: "avatar_3",
    address: "Calle Principal 123, Antofagasta",
    emergencyContact: "Carlos González +56 9 8765 4321",
    notes: "Pendiente de aprobación",
    formaDePago: "contado",
    membership: {
      id: "mem_maria_001",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Básico",
      monthlyPrice: 35000,
      startDate: "2025-01-15",
      currentPeriodStart: "2025-01-15",
      currentPeriodEnd: "2025-02-15",
      planConfig: {
        classLimit: 8,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 8,
          remainingClasses: 8,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-01-15",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Carlos Ruiz (VENCE PRONTO - 3 días)
  {
    id: "usr_carlos_ruiz_001",
    firstName: "Carlos",
    lastName: "Ruiz",
    email: "carlos@email.com",
    phone: "+56 9 9988 7766",
    dateOfBirth: "1988-03-15",
    gender: "Masculino",
    avatarId: "avatar_4",
    address: "Avenida Costanera 789, Antofagasta",
    emergencyContact: "María Ruiz +56 9 8877 6655",
    notes: "Membresía vence pronto, contactar para renovación.",
    formaDePago: "credito",
    membership: {
      id: "mem_carlos_ruiz_001",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Básico",
      planId: "plan_basico_001",
      monthlyPrice: 35000,
      startDate: "2024-12-01",
      currentPeriodStart: "2024-12-01",
      currentPeriodEnd: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)
        .toISOString()
        .split("T")[0], // Vence en 3 días
      planConfig: {
        classLimit: 8,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 6,
          classesContracted: 8,
          remainingClasses: 2,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 1,
        memberSince: "2024-12-01",
        lifetimeStats: {
          totalClasses: 6,
          totalNoShows: 0,
          averageMonthlyAttendance: 6,
          bestMonth: { month: "Diciembre", year: 2024, count: 6 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 1 (ACTIVE)
  {
    id: "usr_test_student_001",
    firstName: "Test",
    lastName: "Student 1",
    email: "test.student1@email.com",
    phone: "+56 9 1000 0001",
    dateOfBirth: "1995-01-01",
    gender: "Otro",
    avatarId: "avatar_1",
    address: "Calle Falsa 123, Ciudad",
    emergencyContact: "Contacto 1 +56 9 2000 0001",
    notes: "Alumno de prueba 1",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_001",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-01-01",
      currentPeriodStart: "2024-01-01",
      currentPeriodEnd: "2024-01-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-01-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 2 (PENDING)
  {
    id: "usr_test_student_002",
    firstName: "Test",
    lastName: "Student 2",
    email: "test.student2@email.com",
    phone: "+56 9 1000 0002",
    dateOfBirth: "1995-02-02",
    gender: "Otro",
    avatarId: "avatar_2",
    address: "Calle Falsa 124, Ciudad",
    emergencyContact: "Contacto 2 +56 9 2000 0002",
    notes: "Alumno de prueba 2",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_002",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-02-01",
      currentPeriodStart: "2024-02-01",
      currentPeriodEnd: "2024-02-28",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-02-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 3 (ACTIVE)
  {
    id: "usr_test_student_003",
    firstName: "Test",
    lastName: "Student 3",
    email: "test.student3@email.com",
    phone: "+56 9 1000 0003",
    dateOfBirth: "1995-03-03",
    gender: "Otro",
    avatarId: "avatar_3",
    address: "Calle Falsa 125, Ciudad",
    emergencyContact: "Contacto 3 +56 9 2000 0003",
    notes: "Alumno de prueba 3",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_003",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-03-01",
      currentPeriodStart: "2024-03-01",
      currentPeriodEnd: "2024-03-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-03-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 4 (PENDING)
  {
    id: "usr_test_student_004",
    firstName: "Test",
    lastName: "Student 4",
    email: "test.student4@email.com",
    phone: "+56 9 1000 0004",
    dateOfBirth: "1995-04-04",
    gender: "Otro",
    avatarId: "avatar_4",
    address: "Calle Falsa 126, Ciudad",
    emergencyContact: "Contacto 4 +56 9 2000 0004",
    notes: "Alumno de prueba 4",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_004",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-04-01",
      currentPeriodStart: "2024-04-01",
      currentPeriodEnd: "2024-04-30",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-04-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 5 (ACTIVE)
  {
    id: "usr_test_student_005",
    firstName: "Test",
    lastName: "Student 5",
    email: "test.student5@email.com",
    phone: "+56 9 1000 0005",
    dateOfBirth: "1995-05-05",
    gender: "Otro",
    avatarId: "avatar_1",
    address: "Calle Falsa 127, Ciudad",
    emergencyContact: "Contacto 5 +56 9 2000 0005",
    notes: "Alumno de prueba 5",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_005",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-05-01",
      currentPeriodStart: "2024-05-01",
      currentPeriodEnd: "2024-05-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-05-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 6 (PENDING)
  {
    id: "usr_test_student_006",
    firstName: "Test",
    lastName: "Student 6",
    email: "test.student6@email.com",
    phone: "+56 9 1000 0006",
    dateOfBirth: "1995-06-06",
    gender: "Otro",
    avatarId: "avatar_2",
    address: "Calle Falsa 128, Ciudad",
    emergencyContact: "Contacto 6 +56 9 2000 0006",
    notes: "Alumno de prueba 6",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_006",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-06-01",
      currentPeriodStart: "2024-06-01",
      currentPeriodEnd: "2024-06-30",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-06-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 7 (ACTIVE)
  {
    id: "usr_test_student_007",
    firstName: "Test",
    lastName: "Student 7",
    email: "test.student7@email.com",
    phone: "+56 9 1000 0007",
    dateOfBirth: "1995-07-07",
    gender: "Otro",
    avatarId: "avatar_3",
    address: "Calle Falsa 129, Ciudad",
    emergencyContact: "Contacto 7 +56 9 2000 0007",
    notes: "Alumno de prueba 7",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_007",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "active",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-07-01",
      currentPeriodStart: "2024-07-01",
      currentPeriodEnd: "2024-07-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
  // Test Student 8 (PENDING)
  {
    id: "usr_test_student_008",
    firstName: "Test",
    lastName: "Student 8",
    email: "test.student8@email.com",
    phone: "+56 9 1000 0008",
    dateOfBirth: "1995-08-08",
    gender: "Otro",
    avatarId: "avatar_4",
    address: "Calle Falsa 130, Ciudad",
    emergencyContact: "Contacto 8 +56 9 2000 0008",
    notes: "Alumno de prueba 8",
    formaDePago: "debito",
    membership: {
      id: "mem_test_student_008",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2024-08-01",
      currentPeriodStart: "2024-08-01",
      currentPeriodEnd: "2024-08-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2024-08-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
    },
    globalPreferences: {},
    globalStats: {},
  },
];

// Agregar 8 alumnos nuevos (Simpsons)
export const simpsonsAlumnos: FitCenterUserProfile[] = [
  {
    id: "usr_homer_simpson",
    firstName: "Homer",
    lastName: "Simpson",
    email: "homer@springfield.com",
    phone: "+1 555-0001",
    membership: {
      id: "mem_homer",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full",
      planId: "plan_full_001",
      monthlyPrice: 50000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_marge_simpson",
    firstName: "Marge",
    lastName: "Simpson",
    email: "marge@springfield.com",
    phone: "+1 555-0002",
    membership: {
      id: "mem_marge",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Intermedio",
      planId: "plan_intermedio_001",
      monthlyPrice: 42500,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 15,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 15,
          remainingClasses: 15,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_bart_simpson",
    firstName: "Bart",
    lastName: "Simpson",
    email: "bart@springfield.com",
    phone: "+1 555-0003",
    membership: {
      id: "mem_bart",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Básico",
      planId: "plan_basico_001",
      monthlyPrice: 35000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 10,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 10,
          remainingClasses: 10,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_lisa_simpson",
    firstName: "Lisa",
    lastName: "Simpson",
    email: "lisa@springfield.com",
    phone: "+1 555-0004",
    membership: {
      id: "mem_lisa",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Full AM",
      planId: "plan_full_am_001",
      monthlyPrice: 40000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 24,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 24,
          remainingClasses: 24,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_maggie_simpson",
    firstName: "Maggie",
    lastName: "Simpson",
    email: "maggie@springfield.com",
    phone: "+1 555-0005",
    membership: {
      id: "mem_maggie",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Básico AM",
      planId: "plan_basico_am_001",
      monthlyPrice: 28000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 10,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 10,
          remainingClasses: 10,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_grandpa_simpson",
    firstName: "Abraham",
    lastName: "Simpson",
    email: "grandpa@springfield.com",
    phone: "+1 555-0006",
    membership: {
      id: "mem_grandpa",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Trimestral",
      planId: "plan_trimestral_001",
      monthlyPrice: 90000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-09-30",
      planConfig: {
        classLimit: 30,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 30,
          remainingClasses: 30,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_milhouse_vanhouten",
    firstName: "Milhouse",
    lastName: "Van Houten",
    email: "milhouse@springfield.com",
    phone: "+1 555-0007",
    membership: {
      id: "mem_milhouse",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "Semestral",
      planId: "plan_semestral_001",
      monthlyPrice: 150000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-12-31",
      planConfig: {
        classLimit: 60,
        disciplineAccess: "all",
        allowedDisciplines: [],
        canFreeze: true,
        freezeDurationDays: 7,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 60,
          remainingClasses: 60,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
  {
    id: "usr_ned_flanders",
    firstName: "Ned",
    lastName: "Flanders",
    email: "ned@springfield.com",
    phone: "+1 555-0008",
    membership: {
      id: "mem_ned",
      organizationId: "org_blacksheep_001",
      organizationName: "BlackSheep CrossFit",
      status: "pending",
      membershipType: "CrossBalance",
      planId: "plan_crossbalance_001",
      monthlyPrice: 30000,
      startDate: "2025-07-01",
      currentPeriodStart: "2025-07-01",
      currentPeriodEnd: "2025-07-31",
      planConfig: {
        classLimit: 8,
        disciplineAccess: "limited",
        allowedDisciplines: ["disc_crossbalance_001"],
        canFreeze: false,
        freezeDurationDays: 0,
        autoRenews: true,
      },
      centerStats: {
        currentMonth: {
          classesAttended: 0,
          classesContracted: 8,
          remainingClasses: 8,
          noShows: 0,
          lastMinuteCancellations: 0,
        },
        totalMonthsActive: 0,
        memberSince: "2025-07-01",
        lifetimeStats: {
          totalClasses: 0,
          totalNoShows: 0,
          averageMonthlyAttendance: 0,
          bestMonth: { month: "N/A", year: 0, count: 0 },
        },
      },
      centerConfig: {
        allowCancellation: true,
        cancellationHours: 2,
        maxBookingsPerDay: 2,
        autoWaitlist: false,
      },
    },
  },
];

// Al final, concatena estos alumnos a initialUsers o donde corresponda

// Clases iniciales - Array vacío para que se generen dinámicamente desde los horarios de las disciplinas
export const initialClasses: ClassSession[] = [];

// Clases extendidas con datos históricos - Array vacío para generación dinámica
export const initialClassSessionsExtended: ClassSessionExtended[] = [];

// === SLIDES DEL CARRUSEL ESTÁTICO ===
export interface CarouselSlide {
  id: string;
  title: string;
  description: string;
  // imageUrl: string; // Eliminado
  ClassStyleADD: string; // Clase CSS para el degradado
  buttonText?: string;
  buttonLink?: string;
}

export const staticCarouselSlides: CarouselSlide[] = [
  {
    id: "slide-1",
    title: "CrossFit",
    description: "Entrenamiento funcional de alta intensidad",
    // imageUrl: "/placeholder.jpg", // Eliminado
    ClassStyleADD: "bg-gradient-to-r from-red-500 to-orange-500",
    buttonText: "Ver Horarios",
    buttonLink: "/app/calendar",
  },
  {
    id: "slide-2",
    title: "Weightlifting",
    description: "Levantamiento de pesas olímpico",
    // imageUrl: "/placeholder.jpg", // Eliminado
    ClassStyleADD: "bg-gradient-to-r from-violet-200 to-pink-200",
    buttonText: "Ver Horarios",
    buttonLink: "/app/calendar",
  },
  {
    id: "slide-3",
    title: "Cross Balance",
    description: "Equilibrio y control corporal",
    // imageUrl: "/placeholder.jpg", // Eliminado
    ClassStyleADD: "bg-gradient-to-r from-emerald-400 to-cyan-400",
    buttonText: "Ver Horarios",
    buttonLink: "/app/calendar",
  },
  {
    id: "slide-4",
    title: "Nuevos Miembros",
    description: "¡Únete a nuestra comunidad!",
    // imageUrl: "/placeholder.jpg", // Eliminado
    ClassStyleADD: "bg-gradient-to-r from-emerald-500 to-emerald-900",
    buttonText: "Registrarse",
    buttonLink: "/app",
  },
];

// === CLASES MOCK PARA USUARIOS ACTIVOS (9-12 JULIO 2025) ===
export const mockActiveUserClasses: ClassSession[] = [
  // 9 de Julio 2025 (Miércoles)
  {
    id: "cls_20250709_0545_crossfit_001",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-09T05:45:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_antonia_abc123", "usr_pedro_perez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250709_0810_crossfit_002",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-09T08:10:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_camilo_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_maria_gonzalez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250709_1130_pilates_001",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_pilates_001",
    name: "Pilates",
    dateTime: "2025-07-09T11:30:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_manu_001",
    capacity: 12,
    registeredParticipantsIds: ["usr_antonia_abc123"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250709_1800_crossfit_003",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-09T18:00:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: [
      "usr_pedro_perez_001",
      "usr_maria_gonzalez_001",
    ],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  // 10 de Julio 2025 (Jueves)
  {
    id: "cls_20250710_0545_crossfit_004",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-10T05:45:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_antonia_abc123"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250710_0810_crossfit_005",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-10T08:10:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_camilo_001",
    capacity: 15,
    registeredParticipantsIds: [
      "usr_pedro_perez_001",
      "usr_maria_gonzalez_001",
    ],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250710_1130_pilates_002",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_pilates_001",
    name: "Pilates",
    dateTime: "2025-07-10T11:30:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_manu_001",
    capacity: 12,
    registeredParticipantsIds: ["usr_antonia_abc123", "usr_pedro_perez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250710_1900_crossfit_006",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-10T19:00:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_maria_gonzalez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  // 11 de Julio 2025 (Viernes)
  {
    id: "cls_20250711_0545_crossfit_007",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-11T05:45:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_antonia_abc123", "usr_pedro_perez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250711_0810_crossfit_008",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-11T08:10:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_camilo_001",
    capacity: 15,
    registeredParticipantsIds: ["usr_maria_gonzalez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250711_1130_pilates_003",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_pilates_001",
    name: "Pilates",
    dateTime: "2025-07-11T11:30:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_manu_001",
    capacity: 12,
    registeredParticipantsIds: ["usr_antonia_abc123"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250711_1800_crossfit_009",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossfit_001",
    name: "CrossFit",
    dateTime: "2025-07-11T18:00:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_vito_001",
    capacity: 15,
    registeredParticipantsIds: [
      "usr_pedro_perez_001",
      "usr_maria_gonzalez_001",
    ],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  // 12 de Julio 2025 (Sábado)
  {
    id: "cls_20250712_1000_crossbalance_001",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_crossbalance_001",
    name: "Cross Balance",
    dateTime: "2025-07-12T10:00:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_manu_001",
    capacity: 12,
    registeredParticipantsIds: ["usr_antonia_abc123", "usr_pedro_perez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250712_1130_weightlifting_001",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_weightlifting_001",
    name: "Weightlifting",
    dateTime: "2025-07-12T11:30:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_camilo_001",
    capacity: 10,
    registeredParticipantsIds: ["usr_maria_gonzalez_001"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
  {
    id: "cls_20250712_1130_pilates_004",
    organizationId: "org_blacksheep_001",
    disciplineId: "disc_pilates_001",
    name: "Pilates",
    dateTime: "2025-07-12T11:30:00-04:00",
    durationMinutes: 60,
    instructorId: "inst_manu_001",
    capacity: 12,
    registeredParticipantsIds: ["usr_antonia_abc123"],
    waitlistParticipantsIds: [],
    status: "scheduled",
    notes: "Clase mock para usuarios activos",
  },
];
